title: Personal Homepage
page-top-title: 个人主页
top-section-bg-text: Be finite  Be infinite.
home-subtitle: 个人简介
copyright-text: '&copy; 2020-2026. All Rights Reserved.'

params:
  customCSS:
    - "css/custom.css"